### ISSUE TITLE
what should be the best value for p_holdout for real data? 

### ISSUE THREAD

**Issue by smilesun** [agisga/ThresholdoutAUC#2]
p_holdout = p_holdout in 
https://github.com/DIDSR/ThresholdoutAUC/blob/a5a3030fc53e1ab70b4e003ccc3b64cd496ec68e/thresholdout_simulation/general_simulation.R#L47

**Comment by agisga** [comment]
In the simulated (holdout) data `p_holdout` is a vector of probabilities P(y = 1) for each observation. That is, y_holdout is Bernoulli(p_holdout). Here is an example of the distribution for the p parameters: https://github.com/DIDSR/ThresholdoutAUC/blob/master/visualizations/img/probs_hist.pdf

Naturally, for real data you don't know what are those probabilities. So if you use real data, then you can just remove all code that refers to `p_holdout`.

In fact, `p_holdout` is included into `general_simulation.R` for the only purpose to compute what would be the maximal theoretically possible AUC that a classifier could achieve, see [`perfect_auc` here](https://github.com/DIDSR/ThresholdoutAUC/blob/a5a3030fc53e1ab70b4e003ccc3b64cd496ec68e/functions/fit_model_for_every_subset.R#L44), which cannot be computed on real data. Other than data generation and computation of "perfect AUC", `p_holdout` is not necessary to run any other part of the simulation (such as computing the AUC on train, holdout, and test data in each  round of learning).
