### ISSUE TITLE
what should be a good choice of n_adapt_rounds for real data? 

### ISSUE THREAD

**Issue by smilesun** [agisga/ThresholdoutAUC#3]
I refactored your code to fit real data, do you think the result make sense or how can we interpret that? if my refactor is right. 

Here I used 10 rounds, is there a recommendation of how many rounds should be chosen? 

```
  n_train round dataset   auc method num_features holdout_access_…
     <int> <dbl> <chr>   <dbl> <chr>         <int>            <dbl>
 1      50     0 cv_auc  0.858 glm               2                0
 2      55     1 cv_auc  0.686 glm               6              129
 3      60     2 cv_auc  0.769 glm               9               17
 4      65     3 cv_auc  0.675 glm               9                3
 5      70     4 cv_auc  0.766 glm              10              129
 6      75     5 cv_auc  0.661 glm              10               33
 7      80     6 cv_auc  0.762 glm              12              257
 8      85     7 cv_auc  0.713 glm              15              513
 9      90     8 cv_auc  0.743 glm              17              129
10      95     9 cv_auc  0.828 glm              19              129
# ... with 67 more rows, and 2 more variables: cum_holdout_access_count <dbl>,
#   cum_budget_decrease_by_round <dbl>
```

**Comment by agisga** [comment]
My purpose for this simulation was to show that machine learning algorithms can overfit to the test dataset if it used more than one time, and to show how the ThresholdoutAUC procedure reduces that danger of overfitting.
The more "rounds of adaptive learning" are performed (`n_adapt_rounds`), the more often the test data is re-used, and so the larger the observed overfitting behavior will be.

So, what value to set for `n_adapt_rounds` will depend on what is your purpose for running this computational experiment.
If, like in my case, you want to explore the overfitting to a test dataset that is used more than once, then even a small `n_adapt_rounds` value is sufficient to see overfitting; for example, see this figure: https://github.com/DIDSR/ThresholdoutAUC/blob/master/visualizations/img/naive_holdout_reuse_vs_thresholdout_AUC_landscape.pdf where `n_adapt_rounds = 30` determines the range of the x-axis, and overfitting can already be observed at round 1.
